
name: Github actions

on: push

jobs:

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - run: echo "Build project"

    test:
        needs: build
        name: Test
        runs-on: ubuntu-latest
        steps:
            - run: echo "Test project"

   



